import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./nav/Navbar";
import Footer from "./footer/Footer";

const PoppinSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "FMX E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#D9E1E9] w-full h-screen">
      <body className={`${PoppinSans.className} `}>
        <div className="flex flex-col min-h-screen">
          {" "}
          <Navbar />
          <main className="flex-grow "> {children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
